### ISSUE TITLE
Non-ASCII metadata strings get encoded incorrectly

### ISSUE THREAD

**Issue by sapir** [J-F-Liu/lopdf#110]
Currently, strings get written (and read?) as UTF-8.

I found that PDF 32000-1:2008 section 7.9.2.2 says that all strings should either begin with `b"\xfe\xff"` and be interpreted as UTF-16BE, or else be interpreted as PDFDocEncoding.

So basically, if I set a non-ASCII document title, I get gibberish. Doing the encoding "manually" (i.e. in my code) as UTF-16BE fixes it. But maybe it would be better if all strings were handled correctly automatically.

**Comment by lrosenthol** [comment]
This is actually a larger problem where the string encoding (UTF16BE, UTF8, PDDocEncoding) isn't tracked or managed in any way by the library so that any/all strings won't display properly.  (I found this by looking at EmbeddedFile names)
