### ISSUE TITLE
[Question] Looking for a crate to parse and extract content from PDF

### ISSUE THREAD

**Issue by k0pernicus** [J-F-Liu/lopdf#12]
First of all: really nice work!
I am looking for a Rust crate to parse a PDF and extract the content from it.
For example, to extract each text line and metadata from the first page, to get which font style and/or font family belongs to the given line, etc.

I am asking if this crate supports a good depth of extraction (for example, if the crate supports already font family and font size extraction for a single line, or word, things like that...).
Can you give me some information about that please?

Thanks a lot

**Comment by jrmuizel** [comment]
I have some really messy code that does something like this: https://github.com/jrmuizel/pdf-info
Currently it dumps a rough html rendering of the glyphs. My goals is to eventually turn it into a usable crate but you may be able use it as a starting point or contribute toward that.

**Comment by k0pernicus** [comment]
Hi @jrmuizel 
Sorry for the delay, and a great thanks for your response :-)
I will look for your project - if you need any help, please to ask ;-)

**Comment by jrmuizel** [comment]
Do you think you sketch out what you'd want the interface to be like. For
example what do you want exposed for fonts?

Perhaps even elaborating on what your larger goal is can give me a better
shape of what your looking for.

**Comment by ErichDonGubler** [comment]
I don't know about @k0pernicus' needs, but I was hoping we could get/make a Rust version of the `pdftotext` from `{poppler,xpdf}-utils` -- I have a small side project in which I'd just like to extract the text itself from the PDFs. At this point, I don't care about fancy stuff like keeping the layouts of the page, but that might be an interesting set of features to iterate on afterwards.

**Comment by jrmuizel** [comment]
My intent is to make https://github.com/jrmuizel/pdf-info capable of doing pdftotext style text extraction. Currently it's capable of producing absolutely positioned text in html for each glyph of the input pdf. It should not be too difficult to modify to produce plain text.

I have some more work to do on text extraction and positioning. After that I plan on making it more robust and usable as a library.

**Comment by jrmuizel** [comment]
I finished the text extraction and positioning stuff that I had in mind. I'm going to look at building a prototype of pdftotext now.

**Comment by k0pernicus** [comment]
@jrmuizel Awesome work!
As soon as I finish my project, I can come and help you

**Comment by jrmuizel** [comment]
I have this roughly working now. I haven't tested it very widely and the code is pretty hacky but it does work on some pdfs.

**Comment by jrmuizel** [comment]
I've uploaded the first version of this crate to https://crates.io/crates/pdf-extract

**Comment by J-F-Liu** [comment]
@jrmuizel Great work! I'd like to integrate this into lopdf when I have time.

**Comment by J-F-Liu** [comment]
lopdf already supports extract text.
