### ISSUE TITLE
Dictionary::extend does not merge sub dictionaries

### ISSUE THREAD

**Issue by drahnr** [J-F-Liu/lopdf#120]
Attempting to impl `DCTDecode` support uncovered an issue with `Dictionary::extend` which does not merge sub dictionaries recursively as anticipated.

**Comment by raimundomartins** [comment]
I also expected it to merge the 2 dictionaries. But when extending these two:
```
<</Type /Page/Resources [1 0 R 2 0 R]/XObject <</X1 1 0 R>>>>
<</Type /Page/Resources 3 0 R/XObject <</X2 2 0 R>>>>
```
I obtain
`<</Type /Page/Resources [3 0 R [1 0 R 2 0 R]]/XObject <</X2 2 0 R>>>>`
when I expected
`<</Type /Page/Resources [3 0 R 1 0 R 2 0 R]/XObject <</X2 2 0 R/X1 1 0 R>>>>`
Besides the missing X1, the array is not properly extended. This has an impact on the example PDF merging code if merging 3 PDFs. Notice that if I swap the merging order, I instead obtain:
`<</Type /Pages/Resources [3 0 R 1 0 R 2 0 R]/XObject <</X1 1 0 R>>>>`
The array now merges correctly, but X2 is still missing.
