### ISSUE TITLE
5014.CIDFont_Spec.pdf fails to load

### ISSUE THREAD

**Issue by jrmuizel** [J-F-Liu/lopdf#13]
Trying to load http://www.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5014.CIDFont_Spec.pdf gives Not a valid PDF file (xref_and_trailer).

**Comment by J-F-Liu** [comment]
The xref subsection `3131 75` ends with ' \r' in this file. Commit 5431de fixes this.

**Comment by jrmuizel** [comment]
Can you do a new release too?

**Comment by J-F-Liu** [comment]
Released 0.12.0
