### ISSUE TITLE
Modify catalog?

### ISSUE THREAD

**Issue by NilsIrl** [J-F-Liu/lopdf#133]
I would like to remove the object with as key "PageLabels" from the catalog. How would that be possible?

**Comment by genusistimelord** [comment]
you get the catalog objects ID and then do something like this.

```
if let Ok(x) = document.get_object_mut(catalog_object.0) {
    if let Object::Dictionary(ref mut dict) = x {
        dict.remove(b"PageLabels");
    }
}
```

if its another object that is located within the objects then you can phrase thru them and do a Dictionary lookup till you find the ones that contain it and then do the dict.remove();

**Comment by NilsIrl** [comment]
I attempted this, however, I don't know how to get the ObjectId of the catalog, I tried doing `catalog.0` (where `catalog` was retrieved using `Document::catalog()`), but it says the field is private...

**Comment by genusistimelord** [comment]
so if you are attempting to Modify an existing PDF and not merging you will need to phrase thru the Objects to find the Catalog to get the ID for it and or to modify it.

https://github.com/J-F-Liu/lopdf/blob/master/examples/merge.rs#L101

here is an example as to what merge is doing to get the Catalog so you would load the objects in

You would Load your file and then using document::object for the iterator loop.

**Comment by NilsIrl** [comment]
You can get the example like so: https://docs.rs/lopdf/0.26.0/src/lopdf/document.rs.html#148-153

https://github.com/NilsIrl/handoutify/commit/97405cabaeeb4da6a1b477888797ba4c3d803d01
