### ISSUE TITLE
Lopdf reports incorrect number of pages and incorrect catalog for certain PDFs

### ISSUE THREAD

**Issue by misos1** [J-F-Liu/lopdf#139]
Lopdf fails to notice updated objects for certain PDFs.

Sample pdf file:
[doc.pdf](https://github.com/J-F-Liu/lopdf/files/6124062/doc.pdf)

``` rust
let doc = lopdf::Document::load("doc.pdf").unwrap();
println!("{}", doc.get_pages().len());
println!("{:?}", doc.catalog().unwrap());
```

Output:
```
4
<</Type /Catalog/Pages 11 0 R>>
```

Expected output (second line is approximate):
```
5
<</Type/Catalog/AcroForm 64 0 R/Pages 11 0 R>>
```

**Comment by williamdes** [comment]
AcroForm seems not implemented

**Comment by Heinenen** [comment]
I cannot reproduce the error with the current version 2cf9f9827959529255a855e263d4e638ef860e91.
The output I get from lopdf matches your expected output exactly (except for a single space character):
```
5
<</Type /Catalog/AcroForm 64 0 R/Pages 11 0 R>>
```

**Comment by williamdes** [comment]
@J-F-Liu why can I not find any code references to the word " AcroForm"?
is it implemented or not?

**Comment by Heinenen** [comment]
@williamdes  There probably isn't anything special implemented, but it doesn't need to be in order to count the correct number of pages.

Most things in PDFs just rely on bery basic data types (called Objects), and from a quick look  it seems that this is also the case for AcroForms.

Are you missing a feature in lopdf, or what is your use case?

**Comment by williamdes** [comment]
I wanted to build a pdf sanitizer, and needed to know what is implemented.

Read, filter object types, Write back to disk

**Comment by Heinenen** [comment]
That could be possible to do, but a lot of work on your side would ve required.

Like I said, most things in PDFs rely on Objects (most often Dictionaries), which can be read by lopdf.
However, which keys/values shall be present in those dictionaries is not enforced/checked by lopdf in any way (with the exception of some special dictionaries, like the document catalog).
