### ISSUE TITLE
IBWA05ModelCode_Mar2.pdf does not load

### ISSUE THREAD

**Issue by jrmuizel** [J-F-Liu/lopdf#14]
http://web.archive.org/web/20070317213312/http://www.bottledwater.org/public/pdf/IBWA05ModelCode_Mar2.pdf gives Error { repr: Custom(Custom { kind: InvalidData, error: StringError("Not a valid PDF file (xref_and_trailer).\nMismatch { message: \"expect repeat at least 1 times, found 0 times\", position: 116 }") }) }

**Comment by J-F-Liu** [comment]
The startxref value is wrong in this file:
```
startxref
0
%%EOF
...
startxref
116
%%EOF
```
