### ISSUE TITLE
[Question] Possibility of sanitizing PDFs

### ISSUE THREAD

**Issue by jabra98** [J-F-Liu/lopdf#142]
Hi, is it possible to strip possibly malicious elements (such as JavaScript or OpenAction tags) off a PDF document using this tool?

**Comment by J-F-Liu** [comment]
yes

**Comment by jabra98** [comment]
Cool, could you give me pointers in how to accomplish that?

**Comment by williamdes** [comment]
I am investigating this, and as far as I see `JavaScript` or `OpenAction` seems not implemented.
Do you confirm @J-F-Liu ?

**Comment by J-F-Liu** [comment]
not implemented
