### ISSUE TITLE
imagen not found in `lopdf::xobject

### ISSUE THREAD

**Issue by josejachuf** [J-F-Liu/lopdf#149]
Hi. I am trying to execute that example todged from [1] 

```
use lopdf::Document;
use lopdf::xobject;

fn main() {
    let mut document = Document::load("example.pdf")?;
    document.version = "1.4".to_string();
    
    // If the stream is loaded correctly
    if let Ok(stream) = xobject::image("image.png") {
        // we need a "page_id", the position coordinates and the size of the image
        document.insert_image(page_id, stream, (50.0, 100.0), (800.0, 500.0));
    }
    
    document.save("image.pdf")?;
}
```

but I get this error (that image does not exist in xobject):

```
if let Ok(stream) = lopdf::xobject::image("image.png") {
   |                                       ^^^^^ not found in `lopdf::xobject`
```

Inspecting the code I see that if it exists [2].

Someone could give me a help with this 

Jose

[1] https://www.dariocancelliere.it/blog/2020/09/29/pdf-manipulation-with-rust-and-considerations
[2] https://github.com/J-F-Liu/lopdf/blob/fec4729625312da00243b58db2169168fe4ed65d/src/xobject.rs#L29

**Comment by J-F-Liu** [comment]
Is the image file exists? Try supply full path.

**Comment by josejachuf** [comment]
Hello @J-F-Liu , thank you for your response.

It is not that you can not find the image, it tells me that the **image** function is not in **xobject**. The indication **^^^^^** points to image, what happens is that it moves when I transcribe around here

Now I call it with the absolute path and I get the same error 
```
if let Ok(stream) = lopdf::xobject::image("/absolute/path/image.png") {
   |                                ^^^^^ not found in `lopdf::xobject`
```

**Comment by josejachuf** [comment]
I took the example of the test [1] and the same, can not find image in lopdf::xobject



[1] https://github.com/J-F-Liu/lopdf/blob/fec4729625312da00243b58db2169168fe4ed65d/src/xobject.rs#L93

**Comment by J-F-Liu** [comment]
Enable feature = "embed_image"

**Comment by josejachuf** [comment]
Thaks @J-F-Liu 
this works fine:

> 
lopdf = { version = "0.26.0", features = ["embed_image"] }

Thanks very much!
Jose

**Comment by josejachuf** [comment]
@J-F-Liu A more query. It works well with a JPG image, but with a PNG with transparency does not work. Is there any limitation?

**Comment by J-F-Liu** [comment]
You may read *PDF reference* to find explanation of image transparency.

**Comment by josejachuf** [comment]
Here: https://stackoverflow.com/questions/14220221/how-to-insert-transparent-png-in-pdf
