### ISSUE TITLE
http://www.srl.inf.ethz.ch/workshop2016/Su.pdf does not Load

### ISSUE THREAD

**Issue by jrmuizel** [J-F-Liu/lopdf#15]
Gives StringError("Not a valid PDF file (read object at 0).\nMismatch { message: \"expect repeat at least 1 times, found 0 times\", position: 0 }")

**Comment by J-F-Liu** [comment]
There is a line `0000000000 00000 n ` in xref table.

**Comment by J-F-Liu** [comment]
Commit  a7a35be fixes this.
