### ISSUE TITLE
A 4.6MiB & 28pages PDF takes ~6s to load with the default pom-parser

### ISSUE THREAD

**Issue by Gowee** [J-F-Liu/lopdf#157]
Hi!

I find lopdf extremely slow to load some PDFs. In my case, the PDF is a random article exported from Chinese Wikipedia. It is just of 4.6 MiB size and 28 pages, while a single `lopdf::Document::load` takes roughly 6s to execute in release mode, 15s+ in non-release mode.

The sample PDF ([exported from here](https://zh.wikipedia.org/w/index.php?title=Special:DownloadAsPdf&page=%E9%98%BF%E9%81%93%E5%A4%AB%C2%B7%E5%B8%8C%E7%89%B9%E5%8B%92&action=show-download-screen)):
[Hilter wiki.pdf](https://github.com/J-F-Liu/lopdf/files/7875405/Hilter.wiki.pdf)

Code:
```rust
use lopdf::*;

fn main() {
    let doc = Document::load("./Hilter wiki.pdf").unwrap();
}
```
Then `time cargo run --release` gives:
```
   usr time    6.53 secs  642.00 micros    6.53 secs
   sys time    0.05 secs   72.00 micros    0.05 secs
```

@oxalica finds that by switching to the non-default `nom-parser`, the execution time drops dramatically to << 1s. 

`time cargo run --release` with `lopdf = { version = "*", features = ["chrono_time", "nom_parser"] }` gives:
```
   usr time  125.60 millis    0.00 micros  125.60 millis
   sys time   30.05 millis  773.00 micros   29.28 millis
```

**Comment by ralpha** [comment]
Using [Flamegraph](https://github.com/flamegraph-rs/flamegraph) you can see that most of the time is spend inside of [`pom`](https://crates.io/crates/pom). (Pom was created by the same author)
![Screenshot from 2022-01-24 23-25-04](https://user-images.githubusercontent.com/2608639/150875666-c75d9246-fe74-4358-aeeb-7f09e481b384.png)

Using [`nom`](https://crates.io/crates/nom) will change this significantly. Also the call stacks are **significantly** shorter.

![Screenshot from 2022-01-24 23-24-02](https://user-images.githubusercontent.com/2608639/150875632-3f49a1cc-f74b-48aa-9822-e89db4d7dc96.png)

Looking at this I think the author should consider switching the default to `nom` instead. (if both parsers result in the same output)
It looks like this is also the reason the `nom` parser was added. ( #56 and #60 )

**Comment by J-F-Liu** [comment]
Yes, switching the default to nom is acceptable.
