### ISSUE TITLE
get_pages returns empty on Lifetimes I and II - v0.9.1.pdf

### ISSUE THREAD

**Issue by jrmuizel** [J-F-Liu/lopdf#16]
Loading https://github.com/isocpp/CppCoreGuidelines/raw/master/docs/Lifetimes%20I%20and%20II%20-%20v0.9.1.pdf gives an empty result from get_pages(). Perhaps it has to do with object streams?

**Comment by J-F-Liu** [comment]
Yes, commit 6b13df (get_object() was searching in Xref table, not in the objects) skipped objects in object streams.

**Comment by J-F-Liu** [comment]
I reverted commit 6b13df now.

**Comment by J-F-Liu** [comment]
Fixed by commit 738e4c2.
