### ISSUE TITLE
PNG image insertion clarification

### ISSUE THREAD

**Issue by joshpauline** [J-F-Liu/lopdf#166]
I have seen a few things online relating to adding transparent pngs to pdfs and I know we need to split up the pdf into seperate parts in order to get it working. [Link](https://stackoverflow.com/questions/14220221/how-to-insert-transparent-png-in-pdf)

```    
let mut doc = Document::load_mem(&response_array).unwrap();

    for (page_number, page_id) in doc.get_pages() {
        if page_number == 1 {
            let image_stream = xobject::image("sign.png").unwrap();

            let insert_result =
                doc.insert_image(page_id, image_stream, (250.0, 0.0), (250.0, 75.0));

            if insert_result.is_err() {
                println!("Error")
            }

            println!("{:?} - {:?}", page_number, page_id);
        }
    }

    doc.save("test.pdf").unwrap();
```

This is part of my current implementation however I am not sure how I am meant to split up the pdf. Could anyone give me an example of how it can be done? 

@J-F-Liu

**Comment by ralpha** [comment]
I did implement this, but I did this on a lower level. So it is a bit more involved.
You have to take in the RGBA image and separate the Alpha layer from the image. So you have a RGB and Alpha (black and white) image.
Then you basically add 2 image to the page.
And set the Alpha image as the `SMask`.

You can find some code here: 
https://github.com/ralpha/pdf_signing/blob/5b0a5f45ef2b04360fdbfc4d663fccc30e0d5af5/src/lib.rs#L101:L125
And
https://github.com/ralpha/pdf_signing/blob/master/src/image_xobject.rs

There are a few other ways to get transparency in PDFs, but this worked well for me.

Note that the linked library is WIP and is far from ready and will change in the future (and has a different purpose) so you might not want to add this as a dependency. But feel free to copy the code (or use it as a dependency if you really want).

If you have questions let me know. Hope this helps.

**Comment by joshpauline** [comment]
@ralpha  wow that is awesome! I was actually planning on building the same library for digital signatures using lopdf. 

Thank you very much for your help
