### ISSUE TITLE
Cannot decode LZWDecode

### ISSUE THREAD

**Issue by RazrFalcon** [J-F-Liu/lopdf#177]
Here is TIFF 6 spec which uses LZWDecode: https://web.archive.org/web/20180810205359/https://www.adobe.io/content/udp/en/open/standards/TIFF/_jcr_content/contentbody/download/file.res/TIFF6.pdf

`Stream::decompress_lzw` fails with:
```
Custom { kind: InvalidData, error: "InvalidCode" }
```

I'm not sure if this is `weezl` error or `lopdf`, because older `lzw` version of `lopdf` fails too.

**Comment by genusistimelord** [comment]
the following code I ran using the TIFF6.pdf
```rust
fn get_mut() -> Result<bool> {
    let mut doc = Document::load("assets/TIFF6.pdf")?;
    doc.save("assets/TIFF_saved.pdf")?;
    Ok(true)
}
```
It loaded the document successfully and saved it to without Error. So I suspect it was a weezl bug and this can be closed @J-F-Liu @RazrFalcon

**Comment by RazrFalcon** [comment]
`lopdf` simply ignores `weezl` errors:

https://github.com/J-F-Liu/lopdf/blob/6b04581640e061bfeb39b585e50a7e9d102b8fe2/src/object.rs#L604

**Comment by genusistimelord** [comment]
can you show me how your loading the file to run into this issue?

**Comment by RazrFalcon** [comment]
I'm not "loading" it, I was just testing this crate and saw a warning in the log.

**Comment by Heinenen** [comment]
I can't reproduce this either.
Not in the current version of lopdf, but also not with v0.26 - v0.29.
Using versions that are older than v0.26, lopdf panics, but that's probably due to something else.
