### ISSUE TITLE
Can't parse PDF with comments in content stream

### ISSUE THREAD

**Issue by baarkerlounger** [J-F-Liu/lopdf#192]
```rust
# parser.rs:304

pub fn content(input: &[u8]) -> Option<Content<Vec<Operation>>> {
    (content_space() * operation().repeat(0..).map(|operations| Content { operations }))
        .parse(input)
        .ok()
}
```

Returns only `Some(Content { operations: [Operation { operator: "q", operands: [] }] })` for the attached sample PDF. It seems like it's not able to parse all the content correctly?

[Payslip.pdf](https://github.com/J-F-Liu/lopdf/files/9786945/Payslip.pdf)

**Comment by jrmuizel** [comment]
The content stream has comments in it:
```
q % -- BeginContent
0.75 0 0 -0.75 0 841.92 cm
```

It seems like that's probably where things are going wrong.

**Comment by baarkerlounger** [comment]
@jrmuizel are comments not supported by lopdf or do I need to do something different to account for that?

**Comment by Heinenen** [comment]
This problem seems to no longer occur, at least not with the nom parser. Feel free to reopen the issue if you think the issue persists.
