### ISSUE TITLE
Consider adding wasm[32/64]-unkown-unknown target

### ISSUE THREAD

**Issue by anterpin** [J-F-Liu/lopdf#194]
Consider adding wasm[32/64]-unknown-unkown target to be compilable to WebAssembly.

**Comment by Heinenen** [comment]
Isn't compiling to wasm already possible?
I managed to get it to work, following this tutorial https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_Wasm.
Or what would we need to change in this repository to make it work for your use case?
