### ISSUE TITLE
Add a parser for pdf content streams

### ISSUE THREAD

**Issue by jrmuizel** [J-F-Liu/lopdf#2]
It would be very valuable if lopdf also supported parsing pdf content streams. I'm not sure how easy these are to parse and how well pom would deal with them but it seems like an interesting challenge.

**Comment by J-F-Liu** [comment]
What will you use this feature for, extract text?

**Comment by jrmuizel** [comment]
Thanks. I'm thinking of building a document comparison tool that would extract character locations, sort them, compare them and link back to the original locations.
