### ISSUE TITLE
Improve documentation so that even RUST beginners can understand

### ISSUE THREAD

**Issue by anhtumai** [J-F-Liu/lopdf#216]

**Comment by sww1235** [comment]
I would recommend reading through the [PDF reference manual](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf) **PDF Warning**. It helped me understand a lot of the examples and how they worked. 

Keep in mind, that this is a very low level PDF library, one step above manually writing the pdf data to a file yourself. It takes care of some of the more tedious processes of writing the PDF like handling the document trailer and ID tracking but still expects you to understand the PDF file format specifically. 

If you need something that is more user friendly, I would recommend looking on [crates.io]() for pdf crates that use lopdf as a dependency. There are a few out there that have varying feature sets.
