### ISSUE TITLE
`The following packages contain code that will be rejected by a future version of Rust: nom v6.1.2`

### ISSUE THREAD

**Issue by frederikhors** [J-F-Liu/lopdf#224]
Can I ask you why I'm having this warning in my cargo routine?

`the following packages contain code that will be rejected by a future version of Rust: nom v6.1.2`

**Comment by frederikhors** [comment]
@J-F-Liu would you mind to release with `nom` dependency updated?

Many CI engines broke for that warning.

Sorry to bother you... 🙏

**Comment by J-F-Liu** [comment]
OK
