### ISSUE TITLE
FEATURE REQUEST: exposing `entry` and other methods to `Dictionary`

### ISSUE THREAD

**Issue by jeertmans** [J-F-Liu/lopdf#231]
Hello,

First, many thanks for this great work!

I wrote a small project, [rpdf](https://github.com/jeertmans/rpdf), that uses your crate to deal with PDFs, and I felt like it had a few limitations.

The main one it that `Dictionary` only implements a few of the methods of `LinkedHashMap`. And the one I am particularly interested in is [`entry`](https://docs.rs/linked-hash-map/latest/linked_hash_map/struct.LinkedHashMap.html#method.entry).

Is there a specific reason why `Dictionary` does not implement `Deref<Target = LinkedHashMap>`?
Or that the inner attribute is private?

Thanks in advance!

**Comment by J-F-Liu** [comment]
Because previously there is no such a need, it's ok to add an `as_hashmap` or `to_hashmap` convertion method.
