### ISSUE TITLE
document.get_pages() returns zero pages

### ISSUE THREAD

**Issue by Vazgen005** [J-F-Liu/lopdf#248]
![image](https://github.com/J-F-Liu/lopdf/assets/70487205/183ec832-76c6-4f47-803f-dd4cdfcff08f)
------
# [download test.pdf](https://cdn.discordapp.com/attachments/911996357479395388/1153434919503142943/test.pdf)

**Comment by Sanceilaks** [comment]
Same

**Comment by bozkayasalihx** [comment]
yeah, i've looked that too. i think its all about document language, lopdf couldn't create btree map of content that way it's throws error

**Comment by Heinenen** [comment]
This may be a bug in the `pom_parser`. You can try switching to the feature `nom_parser` (which has a better performance and is now also the default) and see if that fixes it.

**Comment by Heinenen** [comment]
This issue may already be fixed by #254.
In any case, the download link expired and I can't reproduce it.
