### ISSUE TITLE
Can releases have a GitHub release too ?

### ISSUE THREAD

**Issue by williamdes** [J-F-Liu/lopdf#259]
Hello, 
I noticed that recent tags in 2023 do not have GitHub releases, this makes the project less active than it really is and users subscribed to releases are not notified.

Would you mind publishing the latest one or all of the missing ones ?

Have a nice day
And thank you for maintaining this library !

**Comment by williamdes** [comment]
What do you think @J-F-Liu ?

**Comment by J-F-Liu** [comment]
I need to add some Collaborators to help me manage this repo. 
So volunteers please comment here.

**Comment by williamdes** [comment]
Sure, please add me
I forgot this repo was in Rust.

**Comment by Heinenen** [comment]
I can try to help out a bit as well.
This would be especially helpful to clean up the issue tracker a bit.

**Comment by J-F-Liu** [comment]
Sent invite, thank you all.

**Comment by williamdes** [comment]
Awesome, how do we proceed for releases? 
Are you the only one to be allowed to do them?

Maybe you should add some security rules on tag creation for this repo
Personally I will always GPG sign my commits and tags.

**Comment by J-F-Liu** [comment]
You can try various operations and see if something is blocking.
Please direct me if I need to change some settings of the repo.

**Comment by Heinenen** [comment]
@williamdes Do I understand it correctly that this issue has been resolved?

**Comment by williamdes** [comment]
> @williamdes Do I understand it correctly that this issue has been resolved?

https://github.com/J-F-Liu/lopdf/releases/tag/v0.34.0 is the first release fixing this since 2019, thanks !

That said, GPG signing of commits and tags is still something that would be nice to be considered
https://github.com/J-F-Liu/lopdf/tags

**Comment by williamdes** [comment]
Hi @J-F-Liu 
Can you announce the last release?

**Comment by williamdes** [comment]
Awesome, that said I do not see an announcement on https://github.com/J-F-Liu/lopdf/releases
but I can do it myself since I have some rights on the repository
Will do that soon for the two last releases
