### ISSUE TITLE
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 0).\nMismatch { message: \"expect repeat at least 1 times, found 0 times\", position: 0 }") }

### ISSUE THREAD

**Issue by jrmuizel** [J-F-Liu/lopdf#26]
Using https://github.com/isocpp/CppCoreGuidelines/raw/master/docs/Lifetimes%20I%20and%20II%20-%20v0.9.1.pdf

target/debug/pdfutil print_streams -i "Lifetimes I and II - v0.9.1.pdf"
Open Lifetimes I and II - v0.9.1.pdf
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 0).\nMismatch { message: \"expect repeat at least 1 times, found 0 times\", position: 0 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 0).\nMismatch { message: \"expect repeat at least 1 times, found 0 times\", position: 0 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 0).\nMismatch { message: \"expect repeat at least 1 times, found 0 times\", position: 0 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 0).\nMismatch { message: \"expect repeat at least 1 times, found 0 times\", position: 0 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 0).\nMismatch { message: \"expect repeat at least 1 times, found 0 times\", position: 0 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 0).\nMismatch { message: \"expect repeat at least 1 times, found 0 times\", position: 0 }") }

**Comment by J-F-Liu** [comment]
I can't reproduce this error: 
```
> ./target/debug/pdfutil decompress -i "/Users/Junfeng/Downloads/Lifetimes I and II - v0.9.1.pdf" -o decompressed.pdf
Open /Users/Junfeng/Downloads/Lifetimes I and II - v0.9.1.pdf
Do decompress
Save to decompressed.pdf
```

**Comment by J-F-Liu** [comment]
There are `0000000000 00000 n ` lines in xref section.
