### ISSUE TITLE
http://www.faithaliveresources.org/Content/Site135/FilesSamples/105315400440pdf_00000009843.pdf does not load 

### ISSUE THREAD

**Issue by jrmuizel** [J-F-Liu/lopdf#27]
It gives: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: StringError("corrupt deflate stream") }', libcore/result.rs:945:5

**Comment by J-F-Liu** [comment]
The error is from decoding 359 0 obj, need to confirm whether is stream content is valid deflate stream or not.

**Comment by J-F-Liu** [comment]
Duplicate of #43
