### ISSUE TITLE
Some Pdf Parse Outline Failed

### ISSUE THREAD

**Issue by ZLATAN628** [J-F-Liu/lopdf#270]
I am working on my personal project (https://github.com/ZLATAN628/pdf-terminal-reader) which involves reading PDF files in the terminal. However, I have encountered a problem parsing outlines for this specific PDF: [rust-book-zh-cn-shieber.pdf](https://github.com/J-F-Liu/lopdf/files/14751488/rust-book-zh-cn-shieber.pdf).   

When debugging the get_outlines function, I discovered that the issue arises because the Action tag is treated as a Dictionary, not a Reference, contrary to what I expected. According to the PDF documentation, this behavior is permitted.

Therefore, I attempted to modify the function as follows:  
![img](https://github.com/J-F-Liu/lopdf/assets/107628611/dfb30fe7-0b00-4f45-a0cb-ac8d39c18e81)
This adjustment resolved the issue for me, but I am uncertain about potential negative implications it might have.

**Comment by J-F-Liu** [comment]
This fix is correct.

**Comment by ZLATAN628** [comment]
> This fix is correct.

Thank you for confirming the fix! I have gone ahead and submitted a Pull Request to apply the solution to the project.
