### ISSUE TITLE
Deprecate/remove pom_parser in favor of nom_parser

### ISSUE THREAD

**Issue by Heinenen** [J-F-Liu/lopdf#294]
@J-F-Liu I would like to get your opinion on removing pom_parser, or at least deprecating it.
A concrete problem that prompted this issue is described in https://github.com/J-F-Liu/lopdf/issues/125#issuecomment-2275055483.
#248 probably has the same cause, but the PDF link expired, so I can't check that.

The main advantages we would get when removing one of the parsers:
- reduced code complexity
- increased maintainability
  - no bugs that are only reproducible with one of the parsers
  - no doubled work when implementing new parser features, like #125 

It seems that the nom_parser is the better implementation of the two parser, at least in terms of performance (according to #60 and #208).

**Comment by J-F-Liu** [comment]
It is ok to removing pom_parser to avoid doubled work when implementing new parser features.
Parser code using pom_parser has better readability.

**Comment by Heinenen** [comment]
Ok, thanks for your feedback.
As long as no major additional work or bugs come up, we can probably keep it in and make the final decision only when necessary.
