### ISSUE TITLE
Add support for non-mutable decompression

### ISSUE THREAD

**Issue by jrmuizel** [J-F-Liu/lopdf#3]
The current decompression functionality requires mutating the document. It would be nice to have an api that supports decompression without mutating for consumers that just want to read the document.

**Comment by J-F-Liu** [comment]
Mutation only occurs in memory, it won't modify the file unless you save it.

**Comment by jrmuizel** [comment]
Even though it doesn't actually modify the file it does still require a mut Document which can be a pain. I ended up doing something like this:
https://github.com/jrmuizel/pdf-info/blob/master/src/main.rs#L195

and used a modified lopdf to let me decode content streams that I provide:
https://github.com/jrmuizel/pdf-info/blob/master/src/main.rs#L222

Even if the current decompression functionality remains it would be valuable to expose the content decoding so that it can be done separately from the actual stream object.

**Comment by J-F-Liu** [comment]
Added. Usage like this:
```rust
let content = stream.decompressed_content().unwrap_or(stream.content.clone());
```
Additional clone is required for uncompressed stream.

**Comment by J-F-Liu** [comment]
0.6.0 released
