### ISSUE TITLE
Help: split a pdf file by outlines (bookmarks)

### ISSUE THREAD

**Issue by syssecfsu** [J-F-Liu/lopdf#32]
In my project, I need to split a pdf file by the outlines. Is it possible to do it with lopdf and how if so? Thank you very much!

**Comment by J-F-Liu** [comment]
You can get the page range of each outline, then extract and save the pages into a new file.

**Comment by syssecfsu** [comment]
Thanks for the quick reply. I just figured it out, mostly by referencing the pdfminer source code (it has a dumppdf tool.) 

Just in case someone else wants to solve the same problem. Basically, you need to read the category of the doc and find the Outlines, and follow the objects to find the different levels of the outlines. doc.get_pages() API in lopdf returns the page number to object ID mapping.
