### ISSUE TITLE
Failed parsing PDFs with latest version

### ISSUE THREAD

**Issue by brmmm3** [J-F-Liu/lopdf#330]
With version 0.33 the PDFs getting parsed (more accurately: text extraction) successfully.

Following PDFs fail to extract text with latest version, even with master:

https://github.com/clintel/PDFRenderer/blob/master/doc/32000-1-2008/PDF32000_2008.pdf
[PDF_500_kB.pdf](https://github.com/user-attachments/files/17073413/PDF_500_kB.pdf)

When extracting text from PDF32000_2008.pdf I get:
"PDF32000_2008.pdf" has 407 errors:
"Failed to extract text from page 4 id=(5, 0): ToUnicodeCMap(UnsupportedCodeSpaceRange)"
"Failed to extract text from page 5 id=(7, 0): ToUnicodeCMap(UnsupportedCodeSpaceRange)"
"Failed to extract text from page 19 id=(37, 0): ToUnicodeCMap(Parse(Error))"
"Failed to extract text from page 21 id=(43, 0): ToUnicodeCMap(UnsupportedCodeSpaceRange)"
"Failed to extract text from page 22 id=(45, 0): ToUnicodeCMap(UnsupportedCodeSpaceRange)"
"Failed to extract text from page 23 id=(47, 0): ToUnicodeCMap(UnsupportedCodeSpaceRange)"
"Failed to extract text from page 24 id=(49, 0): ToUnicodeCMap(UnsupportedCodeSpaceRange)"
"Failed to extract text from page 26 id=(53, 0): ToUnicodeCMap(UnsupportedCodeSpaceRange)"
"Failed to extract text from page 27 id=(55, 0): ToUnicodeCMap(UnsupportedCodeSpaceRange)"
"Failed to extract text from page 29 id=(59, 0): ToUnicodeCMap(UnsupportedCodeSpaceRange)"

When extracting text from PDF_500_kB.pdf I get:
thread 'main' panicked at examples/extract_text.rs:161:34:
range end index 10 out of range for slice of length 5

Fixing the text_extract example I get with PDF_500_kB.pdf:
"testdata/PDF_500_kB.pdf" has 5 errors:
"Failed to extract text from page 1 id=(1, 0): ToUnicodeCMap(Parse(Error))"
"Failed to extract text from page 2 id=(4, 0): ToUnicodeCMap(Parse(Error))"
"Failed to extract text from page 3 id=(7, 0): ToUnicodeCMap(Parse(Error))"
"Failed to extract text from page 4 id=(10, 0): ToUnicodeCMap(Parse(Error))"
"Failed to extract text from page 5 id=(14, 0): ToUnicodeCMap(Parse(Error))"

**Comment by Heinenen** [comment]
cc @dkaluza

**Comment by dkaluza** [comment]
Both parse without any errors after:
https://github.com/J-F-Liu/lopdf/pull/328

**Comment by Roba1993** [comment]
This file is unfortunately still crashing for me. Worked with version 0.13 before...
[pdf2.pdf](https://github.com/user-attachments/files/17206965/pdf2.pdf)

**Comment by dkaluza** [comment]
@Roba1993 
Looked into it.

The CMapName for font is defined as:
```
/CMapName /Identity-H
```
Where I believe it should end with `def` according to specification.
(If somebody is better oriented in spec they can correct me)

Again I'm not sure what we should do in that case, is it a common enough error to include it in the parser? I have not encountered it in any other pdf.

Here I guess it is a direct result of the line:
https://github.com/rkusa/pdfjs/blob/41afdfeaa91c32bac54c45eda078fc38a7d720d6/lib/font/otf.js#L186

**Comment by Roba1993** [comment]
@dkaluza 
Thank you for looking into it.

I only use the following function to extract all text from a .pdf file.
`Document::extract_text(&self, page_numbers: &[u32]) -> Result<String>`
My problem is, that the function returns an error when only a single .pdf error occurs.
But it could still be extracted some text from it. Maybe this use-case could be better implemented?

**Comment by dkaluza** [comment]
@Roba1993 

I agree that current interface is not perfect in situations that some fonts are not parsed correctly due to not following the spec or other issues.

I will try to provide a more robust function for such cases with interface similar to:
```
Document::extract_text_fragments(&self, page_numbers: &[u32]) -> Vector<Result<String>>
```
But I do not know if I will manage to do that this week.

**Comment by Roba1993** [comment]
@dkaluza 

Any update on this topic? If not, I could try to implement this function, but I don't know how far I will get. I have never worked within .pdf documents.

**Comment by dkaluza** [comment]
@Roba1993

Sorry, had to focus on other things.
I will try to implement it this weekend. It should not require pdf knowledge just refactor of current extract is needed.

**Comment by dkaluza** [comment]
I have just added PR with refined extraction API.

**Comment by Heinenen** [comment]
Can this issue be closed then?

**Comment by Roba1993** [comment]
@Heinenen For me yes, works like a charm now.
