### ISSUE TITLE
Add changelog?

### ISSUE THREAD

**Issue by dbaynard** [J-F-Liu/lopdf#35]
Hello,

It's difficult to identify what is changing with this library (and as there have been two api changes in as many weeks there's quite a lot to follow).

Would it be possible to add a changelog (ideally for the past few versions)?

**Comment by J-F-Liu** [comment]
Changelog is written in release notes: https://github.com/J-F-Liu/lopdf/releases

**Comment by dbaynard** [comment]
Thanks for that. I'd somehow missed that…
