### ISSUE TITLE
Help: Copy all page content to a new pdf file

### ISSUE THREAD

**Issue by bn3t** [J-F-Liu/lopdf#37]
Hi,
I want to merge pages from 2 pdfs files into one. I already have such a tool that I wrote in GO but I want to rewrite it in Rust using lopdf.

This is the state of where I am: https://gist.github.com/bn3t/1508f3526bc4ca894f818182bf23e602. It tries to copy page 1 of the input document to the doc document but still produces a white page.

Would you be so kind to indicate the step needed to achieve this?

**Comment by J-F-Liu** [comment]
There are many objects related to pages, in Resources. To merge 2 pdf files, merge all the objects, the rearrange trailer, Catalog and Pages objects.

**Comment by yodatak** [comment]
Hi i'm interested in this did you achieve @bn3t  ?

**Comment by bn3t** [comment]
Hi @yodatak, no I didn't make any progress on this. In the meanwhile, I still use a small tool I've wrttten in Go with Unidoc : [pdfmerge](https://github.com/bn3t/pdfmerge)

**Comment by edulix** [comment]
@J-F-Liu is this easy to do? can you provide some tips or some sample code?

**Comment by J-F-Liu** [comment]
I use [pdfunite](http://manpages.ubuntu.com/manpages/bionic/man1/pdfunite.1.html) to do the job.

**Comment by edulix** [comment]
I meant if it is easy to do with `lopdf` library, although thanks for the recommendation.

**Comment by J-F-Liu** [comment]
It is possible, but need to sort out a detailed algorithm.

**Comment by bn3t** [comment]
It seemed far fetched for me to do it with lopdf. I still use the tool I wrote in go and does exactly what I needed: https://github.com/bn3t/pdfmerge.

**Comment by krzysztofgal** [comment]
I tried and failed. Copying content of pages seems to work good, but I cannot get resources to work (they have different structure than original files). I get output without any text, just some lines, tables etc... My understanding at this moment is that to copy pages we need some recursive alg. without using functions like get_page_content/resources (they output flattens original structure) and it seems to be quite big work to do.

**Comment by Emulator000** [comment]
@bn3t @edulix actually I done this.

I created a [PR](https://github.com/J-F-Liu/lopdf/pull/117) with all necessary code.

Once @J-F-Liu will merge it, you'll able to this with this Rust library.

**Comment by robyoung** [comment]
Can this issue be closed now? There is an example for merging PDFs in the docs now.

**Comment by bn3t** [comment]
Yes thanks a lot.
