### ISSUE TITLE
Cannot read pdf document

### ISSUE THREAD

**Issue by manfredlotz** [J-F-Liu/lopdf#39]
When I try to read this document: http://mirror.hmc.edu/ctan/macros/latex/contrib/iwhdp/Back_2015.pdf I get:

Not a valid PDF file (prev xref_and_trailer).
Mismatch { message: "expect repeat at least 1 times, found 0 times", position: 3117 }

**Comment by manfredlotz** [comment]
I forgot to mention that `pdfinfo` doesn't complain

**Comment by J-F-Liu** [comment]
Chrome also cannot open this file.

**Comment by manfredlotz** [comment]
Really?
I have no problem opening it with chrome. My chrome is google-chrome-stable-67.0.3396.99-1.x86_64 in Fedora Linux.

**Comment by J-F-Liu** [comment]
I see a blank blue page in Chrome 69 on Mac book.

**Comment by manfredlotz** [comment]
Yes, this is the content of that pdf document. It is just a background. As said `pdfinfo` doesn't complain about it.

**Comment by manfredlotz** [comment]
Another example where this panic shows up: 
http://academic.brcc.edu/crow/Projects/Calculus%20with%20Infinitesimals/Files/TextbookPdfs/The%20Value%20of%20a%20Hyperreal%20Number.pdf

**Comment by J-F-Liu** [comment]
Fixed by 207a2a91c.

**Comment by manfredlotz** [comment]
I tested on my side. Looks good. Thank you very much for your quick action.
