### ISSUE TITLE
Another panic

### ISSUE THREAD

**Issue by manfredlotz** [J-F-Liu/lopdf#42]
Another panic for http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/bg/description.pdf

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [139], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', libcore/result.rs:945:5

**Comment by J-F-Liu** [comment]
This file contains many non-utf8 dictionary key names, like `/#8b 277 0 R`.

**Comment by manfredlotz** [comment]
Do those names have to be utf8? 

I found another local document on my harddisk showing this error. It was produced by Acrobat Distiller 4.05 for Macintosh in year 2001.

**Comment by J-F-Liu** [comment]
Fixed by 47806f8.

**Comment by manfredlotz** [comment]
Tested. Looks good. Thanks a lot.
