### ISSUE TITLE
Hopefully the last panic

### ISSUE THREAD

**Issue by manfredlotz** [J-F-Liu/lopdf#43]
This document https://www.uspsoig.gov/sites/default/files/document-library-files/2016/RARC-WP-16-001.pdf

gives:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: StringError("corrupt deflate stream") }', libcore/result.rs:945:5

**Comment by manfredlotz** [comment]
I understand. However, as PDF viewers are happy when loading the document what should be the solution.

Perhaps lopdf should have a 'relaxed' option where such oddities are handled gracefully (i.e no panic, only a warning or so). Not sure.

**Comment by J-F-Liu** [comment]
This file is encrypted, so decryption is needed before decompress.

**Comment by manfredlotz** [comment]
Do you plan to implement it?

**Comment by J-F-Liu** [comment]
Yes, but not high priority, maybe in 2019.

**Comment by Heinenen** [comment]
I think decryption is implemented now, and the issue should no longer occur.
Since the document is no longer available, I can't verify that the issue is indeed fixed.

I would suggest closing this issue.
