### ISSUE TITLE
Consider using rust log instead of println

### ISSUE THREAD

**Issue by misos1** [J-F-Liu/lopdf#46]
This would be more robust. Output can be controlled by users of lopdf crate or by users of crates which use lopdf.

https://crates.io/crates/log

There are nice println!-like macros:

* trace!
* debug!
* info!
* warn!
* error!

Printing to stdout can hinder for example usage of lopdf in command line utilities. For example when someone create program to print number of pages to stdout and then want to use it in bash script (or as input to other CLI program) which will do something with that number pulled from stdout. This would hardly work for pdf files that triggers some lopdf warning.

It also looks nicer in code `println!("Warning: {}", err)` -> `warn!("{}", err)`

Or at least print to stderr using eprintln! or use conditional compilation and add feature to turn off printing to stdout.

**Comment by J-F-Liu** [comment]
Fixed.
