### ISSUE TITLE
Corrupt PDF when using the default example [0.6.0]

### ISSUE THREAD

**Issue by sharazam** [J-F-Liu/lopdf#5]
Hi, I made a completely new project and copied the example code.

I had to switch to rust nightly because `#![feature(field_init_shorthand)]` is not allowed on stable. I compiled and ran the get started guide. What I got was a corrupted PDF (I'll attach it if I can).

I do not know why the PDF is corrupted, sadly. It would be nice if someone could look into it.

[Uploading example.pdf.txt…]()

**Comment by J-F-Liu** [comment]
Thanks for trying lopdf, which example are you using, the one in readme file?
You can upload your PDF to https://paste.rs/
```
curl --data-binary @file.txt https://paste.rs/
```
BTW, field_init_shorthand will be available in Rust 1.17.

**Comment by sharazam** [comment]
I'm sorry, GitHub didn't want me to attach files. The file is available at: https://paste.rs/ztf

I created a new project, copy-pasted the code from the README, hit cargo run. This is the result:

```
%PDF-1.5
1 0 obj<</Type/Pages/Kids[5 0 R]/Count 1/Resources 3 0 R/MediaBox[0 0 595 842]>>endobj
2 0 obj<</Type/Font/Subtype/Type1/BaseFont/Courier>>endobj
3 0 obj<</Font<</F1 2 0 R>>>>endobj
4 0 obj<</Length 45>>stream
BT
/F1 48 Tf
100 600 Td
(Hello World!) Tj
ET
endstream endobj
5 0 obj<</Type/Page/Parent 1 0 R/Contents[4 0 R]>>endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000096 00000 n 
0000000155 00000 n 
0000000191 00000 n 
0000000281 00000 n 
trailer
<</Root<</Type/Catalog/Pages 1 0 R>>/Size 6>>
startxref
338
%%EOF
```

There are some things that I wanted to note: Usually, a PDF file has several high-bit characters on the second line, like this:

```
%PDF-1.4
%¥±ë
1 0 obj
```

It doesn't change anything if I add these characters, though. I also wanted to note that this only appears in the default Linux PDF viewer (I think it is called Risetto). pdftk even crashes on this file and Chrome does not want to display it either.

There is certainly something wrong with it, however it displays fine in Adobe Reader.

**Comment by sharazam** [comment]
Just for reference, here is a very similar PDF that is displaying well on all browsers / PDF viewers:

```
%PDF-1.1
%¥±ë

1 0 obj
  << /Type /Catalog
     /Pages 2 0 R
  >>
endobj

2 0 obj
  << /Type /Pages
     /Kids [3 0 R]
     /Count 1
     /MediaBox [0 0 300 144]
  >>
endobj

3 0 obj
  <<  /Type /Page
      /Parent 2 0 R
      /Resources
       << /Font
           << /F1
               << /Type /Font
                  /Subtype /Type1
                  /BaseFont /Times-Roman
               >>
           >>
       >>
      /Contents 4 0 R
  >>
endobj

4 0 obj
  << /Length 55 >>
stream
  BT
    /F1 18 Tf
    0 0 Td
    (Hello World) Tj
  ET
endstream
endobj

xref
0 5
0000000000 65535 f 
0000000018 00000 n 
0000000077 00000 n 
0000000178 00000 n 
0000000457 00000 n 
trailer
  <<  /Root 1 0 R
      /Size 5
  >>
startxref
565
%%EOF
```

see https://brendanzagaeski.appspot.com/0004.html

**Comment by J-F-Liu** [comment]
zathura can open this file, the reason of other readers is that they don't allow Catalog as an direct object in trailer.
I updated my example code now.

**Comment by sharazam** [comment]
Yup, seems to work now, thanks for making this library.
