### ISSUE TITLE
Stream content does not get written when referenced directly, only via reference

### ISSUE THREAD

**Issue by sharazam** [J-F-Liu/lopdf#7]
Stream content (the `Vec<u8>`) does not get written if it is inside another lopdf::Object.
The length gets calculated and written (but the length is wrong, maybe it overflows a certain buffer?), but the following stream corrupts the PDF document and doesn't get handled correctly.

Example - this works correctly (stream as reference):

```rust
use lopdf::{Document as LoDocument, Dictionary as LoDictionary,  Object as LoObject, Stream as LoStream};
use lopdf::Object::*;

let problematic_text = "<xml>test</xml>".to_string()
let mut doc = LoDocument::new();
let stream = Stream(LoStream::new(LoDictionary::from_iter(vec![
    ("Type", "Metadata".into()),
    ("Subtype", "XML".into()), ]),
    problematic_text.as_bytes().to_vec() ));

let catalog = Dictionary(LoDictionary::from_iter(vec![
                      ("Metadata", Reference(doc.add_object(stream)) )]));
doc.add_object(catalog);
doc.save("working.pdf");
```
The above works and the length gets calculated correctly.
Now let's try putting the stream into the catalog as a direct object instead of a reference:
```rust
let mut doc = LoDocument::new();

let catalog = Dictionary(LoDictionary::from_iter(vec![
    ("Metadata", Stream(LoStream::new(
        LoDictionary::from_iter(vec![
            ("Type", "Metadata".into()),
            ("Subtype", "XML".into()), ]),
            problematic_text.as_bytes().to_vec() 
         ))
    )]));
```

This will corrupt the PDF (something with the / and \ is off). It will not create a string and calculate a wrong "Length" for the stream.

I am working on why this is an issue. It's merely inconvenient, I couldn't explain myself why the content doesn't get written.

For reference, here is the full context in which I discovered the issue: https://github.com/sharazam/printpdf/blob/master/src/api/types/pdf_document.rs#L156-L184

It's a bit too big to put it directly in an issue (the repository compiles). `xmp_metadata` is basically [this file](https://github.com/sharazam/printpdf/blob/master/src/templates/catalog_xmp_metadata.txt) with the necessary fields filled out (yes, I know, UTF-8 weirdness). The important part is [Line 156](https://github.com/sharazam/printpdf/blob/master/src/api/types/pdf_document.rs#L156). If you copy-paste the stream inside there, the PDF will get written without error, but it will be corrupt.

**Comment by J-F-Liu** [comment]
According to PDF spec: All streams must be indirect objects and the stream dictionary must be a direct object.

**Comment by sharazam** [comment]
Hm, sorry. This was my fault then. Thanks.
