### ISSUE TITLE
Extract pages as images?

### ISSUE THREAD

**Issue by JonnyTech** [J-F-Liu/lopdf#75]
Is there a method to extract pages in a PDF document as images?

**Comment by jothan** [comment]
No, that would require a full PDF rendering library. lopdf is a low level PDF document handling library.

You may want to look at cairo/poppler or qpdf to do that.

**Comment by JonnyTech** [comment]
As I was just extracting from, not creating, PDF's that this library was sufficient. Many thanks for your reply.
