### ISSUE TITLE
How to get pages numbers and ids

### ISSUE THREAD

**Issue by hasanAjsf** [J-F-Liu/lopdf#79]
I tried the below:
```rust
use lopdf::{Document, Object, Stream};

fn main() {
    println!("Hello, world!");
    let doc = Document::load("HasanResume.pdf").unwrap();
    println!("version: {:#?}, trailer: {:#?}", &doc.version, &doc.trailer);
    let pages = doc.get_pages().iter()
        .map(|page| println!("pagenum: {:#?}, pageid: {:#?}",
                          page.0, page.1)).count();
    println!("{}", pages);
}
```
But got the below:
```bash
    Finished dev [unoptimized + debuginfo] target(s) in 1.13s
     Running `target/debug/read-pdf`
Hello, world!
version: "1.7", trailer: <</Info 92 0 R/Root 1 0 R/Size 93>>
0
```

**Comment by J-F-Liu** [comment]
can you try some other pdf files?

**Comment by hajsf** [comment]
I wish I did no try, the output appeared as below, even the input language of the keyboard had been changed for something new, I turned the PyCharm off, to get the keyboard in English again!

I do not know why this hapened! 

![Screen Shot 2019-09-18 at 10 49 20 PM](https://user-images.githubusercontent.com/46838626/65180933-a3bb6f00-da66-11e9-8b5e-ac1fb49cc27e.png)

**Comment by hajsf** [comment]
I tried again, with a book of 419 pages, and got the same code running, but once I tried to extract the text in (any) page, the app panicked as below:

 
![Screen Shot 2019-09-18 at 11 01 40 PM](https://user-images.githubusercontent.com/46838626/65181775-7bcd0b00-da68-11e9-9ee6-83156b9896e4.png)

The page content is:

![Screen Shot 2019-09-18 at 11 03 35 PM](https://user-images.githubusercontent.com/46838626/65181819-97381600-da68-11e9-9c07-0fd26af4a1d9.png)

**Comment by hajsf** [comment]
I tried with some more files, I noticed the version of all I've is 1.3 or 1.4, but the 2 failed is 1.7, no idea if this have any thing to be fixed, but in all I got the same error:
```bash
version: "1.3", trailer: <</Size 7/Root 1 0 R>>
pagenum: 1, pageid: (
    6,
    0,
)
thread 'main' panicked at 'no entry found for key', src/libcore/option.rs:1034:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Hasans-MacBook-Air:read-pdf hasan$ 
```
and for v1.7:
```bash
Hello, world!
version: "1.7", trailer: <</Info 48 0 R/Root 1 0 R/Size 49>>
thread 'main' panicked at 'no entry found for key', src/libcore/option.rs:1034:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by J-F-Liu** [comment]
Don't print out `doc.trailer`. I tries some file with `println!("version: {:#?}, max_id: {:#?}", &doc.version, &doc.max_id)`, all are ok.

**Comment by Heinenen** [comment]
The problem that produces `?Identity-H` is duplicated in #125.
The other issue is hard to reproduce with the information given and may have been solved.
Feel free to reopen the issue, if it still occurs.
