### ISSUE TITLE
Object::as_datetime() has issues

### ISSUE THREAD

**Issue by svenfoo** [J-F-Liu/lopdf#88]
While working on tests for rsvg-convert (a tool that's built with librsvg), I found several issues with the Object::as_datetime() implementation. Maybe I'm just using this incorrectly ot it's some other misunderstanding, But I would like to raise the issues here.

## Timezone handling

The implementation uses chrono::Local.datetime_from_str(). This method will return an error (ParseError::Impossible)) if the timezone offset in the string doesn't match the local timezone offset. So while this may work for PDF files that are created in the local timezone, it is likely going to fail quite often.

The chrono crate offers another method which is DateTime::parse_from_str():
https://docs.rs/chrono/0.3.0/chrono/datetime/struct.DateTime.html#method.parse_from_str
This method seems more appropriate as it can handle different timezone offsets.

In my opinion it would also make sense to consider changing the return value of Object::as_datetime() to return a DateTime in the UTC offset instead of using Local.

## Parsing of incomplete dates

I've run into problems because the PDF I tested did not specify the minutes of the timezone offset. So the CreationDate string looked like this:
```
D:20200211085039+00'
```
Instead of the proper
```
D:20200211085039+00'00'
```
While this was due to a bug in the library that created the PDF, it still seems valid according to the PDF spec. According to the spec all fields after the year are optional. However the code in Object::as_datetime() will raise ParseError(TooShort) unless the complete datetime string is given. So I think the parser should be changed to deal gracefully with the optional fields missing.

**Comment by J-F-Liu** [comment]
The corresponding code is
```rust
const TIME_FMT_DECODE_STR: &str = "%Y%m%d%H%M%S%z";

Local.datetime_from_str(&text, TIME_FMT_DECODE_STR).ok()

strptime(&text, TIME_FMT_DECODE_STR).ok()
```

**Comment by svenfoo** [comment]
I've opened a pull request to address the non-local timezone issue.

I would also like to point out that it would be desirable if Object::as_datetime() returned DateTime<FixedOffset> because that represents better what's actually in the PDF. The choice of DateTime<Local> is somewhat unfortunate, but I guess it's too late to change that now.

**Comment by svenfoo** [comment]
I've pushed a test here that illustrates that there's still an issue with optional fields:
https://github.com/svenfoo/lopdf/commit/d46d2497

**Comment by svenfoo** [comment]
As explained in #90, most problems are solved now. The remaining issues seem to be rather esoteric and I would like to suggest that this ticket is closed now.

**Comment by J-F-Liu** [comment]
Thanks, released new version.
